import "./globals.css";

import { Geist, Geist_Mono } from "next/font/google";

import LanguageSwitcher from "@/components/LanguageSwitcher";
import { MessagesProvider } from "@/lib/messages-context";
import type { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MessagesProvider>
          <header className="w-full border-b border-black/10 dark:border-white/10 p-4 flex justify-end">
            <LanguageSwitcher />
          </header>
          {children}
        </MessagesProvider>
      </body>
    </html>
  );
}
